---
apiVersion: v2
name: vault
version: 1.0.0
appVersion: 1.15.2
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-helm
  - https://github.com/hashicorp/vault-k8s
  - https://github.com/hashicorp/vault-csi-provider
type: application

dependencies:
- name: vault
  version: 0.27.0
  repository: https://helm.releases.hashicorp.com
